- id: '1610995679644'
  alias: Leaving Home
  description: ''
  trigger:
  - platform: zone
    entity_id: person.sanjit
    zone: zone.home
    event: leave
  condition: []
  action:
  - scene: scene.full_off
  - service: media_player.turn_off
    data: {}
    entity_id: media_player.49_tcl_roku_tv
  - service: media_player.media_pause
    data: {}
    entity_id:
    - media_player.living_room
    - media_player.bedroom
    - media_player.bathroom
    - media_player.living_room_apple_tv
  mode: single
- id: '1610995780479'
  alias: Arriving Home
  description: ''
  trigger:
  - platform: zone
    entity_id: person.sanjit
    zone: zone.home
    event: enter
  condition:
  - condition: or
    conditions:
    - condition: sun
      before: sunrise
      before_offset: 00:45
    - condition: sun
      after: sunset
      after_offset: -00:45
    - condition: state
      entity_id: weather.philadelphia
      state: cloudy,fog,hail,lightning,lightning-rainy,pouring,rainy,snowy,snowy-rainy
  action:
  - scene: scene.full_on
  mode: single
- id: '1610995829321'
  alias: Lights at Sunset
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: -0:45
  condition:
  - condition: zone
    entity_id: person.sanjit
    zone: zone.home
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.full_on
    metadata: {}
  mode: single
- alias: Play/Pause
  description: ''
  trigger:
  - platform: event
    event_type: ios.action_fired
    event_data:
      actionID: play_pause
  action:
    service: media_player.media_play_pause
    entity_id: all
  id: 87254c4006eb4957a40f202cbf2777d4
- alias: Toggle Color Sync
  description: ''
  trigger:
  - platform: event
    event_type: ios.action_fired
    event_data:
      actionID: toggle_color_sync
  action:
    service: input_boolean.toggle
    entity_id: input_boolean.sync_what_s_playing_to_lights
  id: 9acd78b7a1b84990a292f7f72b41e4e2
- alias: Toggle Game Color Sync
  description: ''
  trigger:
  - platform: event
    event_type: ios.action_fired
    event_data:
      actionID: toggle_game_color_sync
  action:
    service: input_boolean.toggle
    entity_id: input_boolean.sync_game_to_lights
  id: 0036c964f55a478e8079807f840c7169
- id: '1665348272400'
  alias: Sleep Focus Turn Lights Off
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.sanjits_iphone_focus
    from: 'off'
    to: 'on'
  condition:
  - condition: state
    entity_id: person.sanjit
    state: home
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.full_off
    metadata: {}
  mode: single
- id: '1681882371302'
  alias: Leaving Home - Vacuum
  description: ''
  trigger:
  - platform: zone
    entity_id: person.sanjit
    zone: zone.home
    event: leave
  condition:
  - condition: numeric_state
    entity_id: vacuum.robovac
    attribute: battery_level
    above: 75
  - condition: state
    entity_id: vacuum.robovac
    state: docked
    for:
      hours: 4
      minutes: 0
      seconds: 0
  - condition: state
    entity_id: input_boolean.auto_vacuum
    state: 'on'
  action:
  - service: vacuum.send_command
    data:
      command: autoClean
    target:
      entity_id: vacuum.robovac
  mode: single
- id: '1681882632828'
  alias: Arriving Home - Vacuum
  description: ''
  trigger:
  - platform: zone
    entity_id: person.sanjit
    zone: zone.home
    event: enter
  condition:
  - condition: not
    conditions:
    - condition: or
      conditions:
      - condition: state
        entity_id: vacuum.robovac
        state: docked
        for:
          hours: 0
          minutes: 0
          seconds: 0
      - condition: state
        entity_id: vacuum.robovac
        state: Charging
  action:
  - service: vacuum.return_to_base
    data: {}
    target:
      entity_id: vacuum.robovac
  mode: single
- id: '1682490301965'
  alias: Daily Vacuum
  description: ''
  trigger:
  - platform: time
    at: '10:00:00'
  condition:
  - condition: not
    conditions:
    - condition: zone
      entity_id: person.sanjit
      zone: zone.home
  - condition: numeric_state
    entity_id: vacuum.robovac
    attribute: battery_level
    above: 75
  - condition: state
    entity_id: vacuum.robovac
    state: docked
    for:
      hours: 22
      minutes: 0
      seconds: 0
  - condition: state
    entity_id: input_boolean.auto_vacuum
    state: 'on'
  action:
  - service: vacuum.send_command
    data:
      command: autoClean
    target:
      entity_id: vacuum.robovac
  mode: single
- alias: bedroom_off
  initial_state: true
  trigger:
  - platform: event
    event_type: ios.action_fired
    event_data:
      actionName: bedroom_off
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.bedroom_off
  id: 4fed1d1d19d245319e7e2e3499f407ff
- alias: bedroom_on
  initial_state: true
  trigger:
  - platform: event
    event_type: ios.action_fired
    event_data:
      actionName: bedroom_on
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.bedroom_on
  id: 0aba6a05ae1d4673beb4fef6721b52c2
- alias: full_off
  initial_state: true
  trigger:
  - platform: event
    event_type: ios.action_fired
    event_data:
      actionName: full_off
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.full_off
  id: e48f5e4544d648c7954017940478630a
- alias: full_on
  initial_state: true
  trigger:
  - platform: event
    event_type: ios.action_fired
    event_data:
      actionName: full_on
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.full_on
  id: a1d545b48ab14dba8af3aabe3e6193d5
- alias: living_room_off
  initial_state: true
  trigger:
  - platform: event
    event_type: ios.action_fired
    event_data:
      actionName: living_room_off
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.living_room_off
  id: 44d9a153626940388811919f0218c2bb
- alias: living_room_on
  initial_state: true
  trigger:
  - platform: event
    event_type: ios.action_fired
    event_data:
      actionName: living_room_on
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.living_room_on
  id: 4e0aac1d64a5424b980a9ee757d82590
- alias: dining
  initial_state: true
  trigger:
  - platform: event
    event_type: ios.action_fired
    event_data:
      actionName: dining
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.dining
  id: cf2b0499f1964c158fa7227db4aa6cb2
- alias: relax
  initial_state: true
  trigger:
  - platform: event
    event_type: ios.action_fired
    event_data:
      actionName: relax
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.relax
  id: fe043c1310214a6b9977aa9e4800dcc5
- alias: theater
  initial_state: true
  trigger:
  - platform: event
    event_type: ios.action_fired
    event_data:
      actionName: theater_mode
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.theater_mode
  id: 51b76f9f9b34474e9e2f9fbc711082da
- alias: work
  initial_state: true
  trigger:
  - platform: event
    event_type: ios.action_fired
    event_data:
      actionName: work
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.work
  id: 2f0d9c51e66e432f976bc3f652be2c63
- id: '1694382443921'
  alias: Sonos I - Living Room
  description: ''
  trigger: []
  condition:
  - condition: or
    conditions:
    - condition: state
      entity_id: media_player.bathroom
      state: playing
    - condition: state
      entity_id: media_player.bedroom
      state: playing
  action:
  - if:
    - condition: or
      conditions:
      - condition: state
        entity_id: media_player.bathroom
        state: playing
      - condition: state
        entity_id: media_player.bedroom
        state: playing
    then:
    - if:
      - condition: state
        entity_id: media_player.bedroom
        state: playing
      then:
      - service: media_player.join
        data:
          group_members:
          - media_player.living_room
        target:
          entity_id: media_player.bedroom
      else:
      - service: media_player.join
        data:
          group_members:
          - media_player.living_room
        target:
          entity_id: media_player.bathroom
    - delay:
        hours: 0
        minutes: 0
        seconds: 2
        milliseconds: 0
    - service: media_player.unjoin
      data: {}
      target:
        entity_id:
        - media_player.bathroom
        - media_player.bedroom
  mode: single
- id: '1694384173969'
  alias: Sonos II - Bedroom
  description: ''
  trigger: []
  condition:
  - condition: or
    conditions:
    - condition: state
      entity_id: media_player.bathroom
      state: playing
    - condition: state
      entity_id: media_player.living_room
      state: playing
  action:
  - if:
    - condition: or
      conditions:
      - condition: state
        entity_id: media_player.bathroom
        state: playing
      - condition: state
        entity_id: media_player.living_room
        state: playing
    then:
    - if:
      - condition: state
        entity_id: media_player.living_room
        state: playing
      then:
      - service: media_player.join
        data:
          group_members:
          - media_player.bedroom
        target:
          entity_id: media_player.living_room
      else:
      - service: media_player.join
        data:
          group_members:
          - media_player.bedroom
        target:
          entity_id: media_player.bathroom
    - delay:
        hours: 0
        minutes: 0
        seconds: 2
        milliseconds: 0
    - service: media_player.unjoin
      data: {}
      target:
        entity_id:
        - media_player.bathroom
        - media_player.living_room
  mode: single
- id: '1694384233538'
  alias: Sonos III - Bathroom
  description: ''
  trigger: []
  condition:
  - condition: or
    conditions:
    - condition: state
      entity_id: media_player.living_room
      state: playing
    - condition: state
      entity_id: media_player.bedroom
      state: playing
  action:
    if:
    - condition: or
      conditions:
      - condition: state
        entity_id: media_player.living_room
        state: playing
      - condition: state
        entity_id: media_player.bedroom
        state: playing
    then:
    - if:
      - condition: state
        entity_id: media_player.bedroom
        state: playing
      then:
      - service: media_player.join
        data:
          group_members:
          - media_player.bathroom
        target:
          entity_id: media_player.bedroom
      else:
      - service: media_player.join
        data:
          group_members:
          - media_player.bathroom
        target:
          entity_id: media_player.living_room
    - delay:
        hours: 0
        minutes: 0
        seconds: 2
        milliseconds: 0
    - service: media_player.unjoin
      data: {}
      target:
        entity_id:
        - media_player.living_room
        - media_player.bedroom
  mode: single
