- id: '1610995679644'
  alias: Leaving Home
  description: ''
  trigger:
  - platform: zone
    entity_id: person.sanjit
    zone: zone.home
    event: leave
  condition: []
  action:
  - scene: scene.full_off
  - service: media_player.turn_off
    data: {}
    entity_id: media_player.49_tcl_roku_tv
  - service: media_player.media_pause
    data: {}
    entity_id:
    - media_player.actually_speakers
    - media_player.all_speakers
    - media_player.bedroom_speaker
    - media_player.bathroom_speaker
    - media_player.bedroom_tv
    - media_player.kitchen_speaker
    - media_player.living_room_speaker
    - media_player.living_room_tv
  mode: single
- id: '1610995780479'
  alias: Arriving Home
  description: ''
  trigger:
  - platform: zone
    entity_id: person.sanjit
    zone: zone.home
    event: enter
  condition:
  - condition: or
    conditions:
    - condition: sun
      before: sunrise
      before_offset: 00:45
    - condition: sun
      after: sunset
      after_offset: -00:45
    - condition: state
      entity_id: weather.philadelphia
      state: cloudy,fog,hail,lightning,lightning-rainy,pouring,rainy,snowy,snowy-rainy
  action:
  - scene: scene.full_on
  mode: single
- id: '1610995829321'
  alias: Lights at Sunset
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: -00:30
  condition:
  - condition: zone
    entity_id: person.sanjit
    zone: zone.home
  action:
  - scene: scene.full_on
  mode: single
- alias: Play/Pause
  description: ''
  trigger:
  - platform: event
    event_type: ios.action_fired
    event_data:
      actionID: play_pause
  action:
    service: media_player.media_play_pause
    entity_id: all
  id: 87254c4006eb4957a40f202cbf2777d4
- alias: Toggle Color Sync
  description: ''
  trigger:
  - platform: event
    event_type: ios.action_fired
    event_data:
      actionID: toggle_color_sync
  action:
    service: input_boolean.toggle
    entity_id: input_boolean.sync_what_s_playing_to_lights
  id: 9acd78b7a1b84990a292f7f72b41e4e2
- alias: Toggle Game Color Sync
  description: ''
  trigger:
  - platform: event
    event_type: ios.action_fired
    event_data:
      actionID: toggle_game_color_sync
  action:
    service: input_boolean.toggle
    entity_id: input_boolean.sync_game_to_lights
  id: 0036c964f55a478e8079807f840c7169
- id: '1665348272400'
  alias: Sleep Focus Turn Lights Off
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.sanjits_iphone_focus
    from: 'off'
    to: 'on'
  condition:
  - condition: state
    entity_id: person.sanjit
    state: home
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.full_off
    metadata: {}
  mode: single
- id: '1681882371302'
  alias: Leaving Home - Vacuum
  description: ''
  trigger:
  - platform: zone
    entity_id: person.sanjit
    zone: zone.home
    event: leave
  condition:
  - condition: numeric_state
    entity_id: vacuum.robovac
    attribute: battery_level
    above: 75
  - condition: state
    entity_id: vacuum.robovac
    state: 'off'
    for:
      hours: 22
      minutes: 0
      seconds: 0
  - condition: state
    entity_id: input_boolean.auto_vacuum
    state: 'on'
  action:
  - service: vacuum.send_command
    data:
      command: autoClean
    target:
      entity_id: vacuum.robovac
  mode: single
- id: '1681882632828'
  alias: Arriving Home - Vacuum
  description: ''
  trigger:
  - platform: zone
    entity_id: person.sanjit
    zone: zone.home
    event: enter
  condition:
  - condition: not
    conditions:
    - condition: or
      conditions:
      - condition: state
        entity_id: vacuum.robovac
        attribute: status
        state: docked
        for:
          hours: 0
          minutes: 0
          seconds: 0
      - condition: state
        entity_id: vacuum.robovac
        attribute: status
        state: charging
  action:
  - service: vacuum.return_to_base
    data: {}
    target:
      entity_id: vacuum.robovac
  mode: single
- id: '1682490301965'
  alias: Daily Vacuum
  description: ''
  trigger:
  - platform: time
    at: '10:00:00'
  condition:
  - condition: not
    conditions:
    - condition: zone
      entity_id: person.sanjit
      zone: zone.home
  - condition: numeric_state
    entity_id: vacuum.robovac
    attribute: battery_level
    above: 75
  - condition: state
    entity_id: vacuum.robovac
    state: 'off'
    for:
      hours: 22
      minutes: 0
      seconds: 0
  - condition: state
    entity_id: input_boolean.auto_vacuum
    state: 'on'
  action:
  - service: vacuum.send_command
    data:
      command: autoClean
    target:
      entity_id: vacuum.robovac
  mode: single
