
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

frontend:
    themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# http:
#   ssl_certificate: /config/certs/fullchain.pem
#   ssl_key: /config/certs/privkey.pem

# spotify:
#     client_id: !secret SPOTIFY_CLIENT_ID
#     client_secret: !secret SPOTIFY_CLIENT_SECRET

recorder:
    purge_keep_days: 2

light:
  - platform: switch
    name: Desk Lights
    entity_id: switch.desk_lights
  - platform: switch
    name: String Lights
    entity_id: switch.string_lights
  - platform: group
    name: Living Room Lights
    entities:
      - light.living_color_lamp_1
      - light.living_color_lamp_2
      - light.living_color_lamp_3
      - light.string_lights
      - light.desk_lights
#     - light.bedroom
  - platform: group
    name: Black Lamp
    entities:
      - light.living_color_lamp_1
      - light.living_color_lamp_2
      - light.living_color_lamp_3

homeassistant:
    media_dirs:
        local: /config/media

# camera:
#   - platform: mjpeg
#     mjpeg_url: http://192.168.1.30:8081/cam_pic_new.php
#     username: "picam"
#     password: "opensesame"
#     name: "Window"

scrape:
    - resource: http://192.168.1.30:1111/noise.html
      scan_interval: 10
      sensor:
          - name: "AC Noise"
            select: "span"

sensor:
#   - platform: scrape
#     resource: http://10.0.0.161:1111/noise.html
#     select: "span"
#     name: "AC Noise"

   - platform: template
     sensors:
       ac_noise_bool:
         value_template: "{{ states('sensor.ac_noise') | float > states('input_number.noise_detection_threshold') | float }}" # use > 1.5 for summer/AC
         friendly_name: "AC Noise (Boolean)"
#       living_room_tv_cc_volume:
#         value_template: "{{ state_attr('media_player.living_room_tv', 'volume_level') | float }}"
#         friendly_name: "Living Room TV Chromecast (Volume)"
#       bedroom_speaker_volume:
#         value_template: "{{ state_attr('media_player.bedroom_speaker', 'volume_level') | float }}"
#         friendly_name: "Bedroom Speaker (Volume)"

#   - platform: scrape
#     resource: http://10.0.0.91:1111/image_url.html
#     select: "span"
#     name: "Game Screenshot URL"

# multiscrape:
#   - resource: http://10.0.0.161:1111/noise.html
#     scan_interval: 10 # seconds
#     sensor:
#       - unique_id: ac_noise
#         name: "AC Noise"
#         select: "span"
#   - resource: http://10.0.0.91:1111/image_url.html
#     scan_interval: 10 # seconds
#     sensor:
#       - unique_id: game_screenshot_url
#         name: "Game Screenshot URL"
#         select: "span"

# template:
#   - binary_sensor:
#       name: "Game Color Sync Active"
#       state: "{{ states('input_boolean.sync_game_to_lights') }}"
#       attributes:
#         entity_picture: >
#           {% if states('input_boolean.sync_game_to_lights') == 'on' %}
#           {{ states('sensor.game_screenshot_url') }}
#           {% else %}
#           
#           {% endif %}

ios:
  actions:
#    - name: bedroom_off
#      background_color: "#000000"
#      label:
#        text: "Bedroom Off"
#        color: "#ddbe00"
#      icon:
#        icon: bed
#        color: "#ddbe00"
#    - name: bedroom_on
#      background_color: "#ddbe00"
#      label:
#        text: "Bedroom On"
#        color: "#000000"
#      icon:
#        icon: bed-empty
#        color: "#000000"
    - name: full_off
      background_color: "#24294F"
      label:
        text: "Full Off"
        color: "#C9CBE5"
      icon:
        icon: lightbulb-off-outline
        color: "#C9CBE5"
    - name: full_on
      background_color: "#4F66A7"
      label:
        text: "Full On"
        color: "#DBE0ED"
      icon:
        icon: lightbulb-on-outline
        color: "#DBE0ED"
#    - name: living_room_off
#      background_color: "#000000"
#      label:
#        text: "Living Room Off"
#        color: "#00bb84"
#      icon:
#        icon: lamps-outline
#        color: "#00bb84"
#    - name: living_room_on
#      background_color: "#00bb84"
#      label:
#        text: "Living Room On"
#        color: "#000000"
#      icon:
#        icon: lamps
#        color: "#000000"
#    - name: dining
#      background_color: "#6F9CCC"
#      label:
#        text: "Dining"
#        color: "#E2EBF5"
#      icon:
#        icon: silverware-fork-knife
#        color: "#E2EBF5"
    - name: living_room_on
      background_color: "#6F9CCC"
      label:
        text: "Living Room"
        color: "#E2EBF5"
      icon:
        icon: lamps
        color: "#E2EBF5"
    - name: relax
      background_color: "#417FCF"
      label:
        text: "Relax"
        color: "#D7E5F5"
      icon:
        icon: spa
        color: "#D7E5F5"
    - name: theater_mode
      background_color: "#828FA6"
      label:
        text: "Theater"
        color: "#E3E6EA"
      icon:
        icon: filmstrip
        color: "#E3E6EA"
    - name: work
      background_color: "#6BA0AC"
      label:
        text: "Work"
        color: "#DCE8EB"
      icon:
        icon: briefcase-outline
        color: "#DCE8EB"
    - name: brightness_up
      background_color: "#C9CBE5"
      label:
        text: "Brighter"
        color: "#24294F"
      icon:
        icon: lightbulb-on
        color: "#24294F"
    - name: brightness_down
      background_color: "#DBE0ED"
      label:
        text: "Dimmer"
        color: "#4F66A7"
      icon:
        icon: lightbulb
        color: "#4F66A7"
    - name: volume_up
      background_color: "#E2EBF5"
      label:
        text: "Louder"
        color: "#6F9CCC"
      icon:
        icon: volume-medium
        color: "#6F9CCC"
    - name: volume_down
      background_color: "#D7E5F5"
      label:
        text: "Softer"
        color: "#417FCF"
      icon:
        icon: volume-low
        color: "#417FCF"
    - name: play_pause
      background_color: "#E6E9ED"
      label:
        text: "Play/Pause"
        color: "#828FA6"
      icon:
        icon: play-pause
        color: "#828FA6"

    - name: play_in_living_room
      background_color: "#24294F"
      label:
        text: "Play in Living Room"
        color: "#C9CBE5"
      icon:
        icon: music-box
        color: "#C9CBE5"
    - name: play_in_bathroom
      background_color: "#4F66A7"
      label:
        text: "Play In Bathroom"
        color: "#DBE0ED"
      icon:
        icon: music-box-outline
        color: "#DBE0ED"
    - name: play_in_bedroom
      background_color: "#6F9CCC"
      label:
        text: "Play in Bedroom"
        color: "#E2EBF5"
      icon:
        icon: music-circle
        color: "#E2EBF5"
    - name: play_turntable
      background_color: "#417FCF"
      label:
        text: "Play Turntable"
        color: "#D7E5F5"
      icon:
        icon: record-player
        color: "#D7E5F5"



    - name: toggle_color_sync
      background_color: "#E0EBEE"
      label:
        text: "Toggle Color Sync"
        color: "#6DA1AD"
      icon:
        icon: palette
        color: "#6DA1AD"

#    - name: toggle_game_color_sync
#      background_color: "#deff91"
#      label:
#        text: "Toggle Game Color Sync"
#        color: "#000000"
#      icon:
#        icon: google-controller
#        color: "#000000"

# Eufy Robovac

# eufy_vacuum:
#  devices:
#  - name: Robovac
#    address: 192.168.0.122
#    access_token: 2lRDw1wuRbuvjfbMKgyrNQ
#    id: 500700082cf432328ee3
#    type: T2118 # T2130
