- id: '1610994719610'
  name: Theater Mode
  entities:
    light.string_lights:
      supported_color_modes:
      - onoff
      friendly_name: String Lights
      supported_features: 0
      state: unavailable
    input_boolean.sync_what_s_playing_to_lights:
      editable: true
      icon: mdi:palette
      friendly_name: Sync What's Playing to Lights?
      state: 'off'
    light.desk_lights:
      supported_color_modes:
      - onoff
      friendly_name: Desk Lights
      supported_features: 0
      state: unavailable
    light.black_lamp:
      supported_color_modes:
      - color_temp
      - xy
      icon: mdi:lightbulb-group
      friendly_name: Black Lamp
      supported_features: 44
      min_color_temp_kelvin: 2000
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 500
      effect_list:
      - None
      - candle
      - fire
      - unknown
      entity_id:
      - light.living_color_lamp_1
      - light.living_color_lamp_2
      - light.living_color_lamp_3
      color_mode: xy
      brightness: 54
      hs_color:
      - 38.438
      - 50.196
      rgb_color:
      - 255
      - 209
      - 127
      xy_color:
      - 0.4498
      - 0.4059
      effect: None
      state: 'on'
    light.bedroom:
      supported_color_modes:
      - brightness
      is_hue_group: true
      hue_scenes:
      - Tropical twilight
      - Dimmed
      - Energize
      - Savanna sunset
      - Mixology
      - Read
      - Concentrate
      - Spring blossom
      - Bright
      - Arctic aurora
      - Nightlight
      - Relax
      hue_type: room
      lights:
      - Bedroom white lamp 1
      dynamics: false
      icon: mdi:lightbulb-group
      friendly_name: Bedroom
      supported_features: 40
      state: 'off'
  icon: mdi:filmstrip
  metadata:
    light.black_lamp:
      entity_only: true
    light.bedroom:
      entity_only: true
- id: '1610994765804'
  name: Full On
  entities:
    input_boolean.sync_what_s_playing_to_lights:
      editable: true
      icon: mdi:palette
      friendly_name: Sync What's Playing to Lights?
      state: 'off'
    light.living_room_lights:
      min_mireds: 153
      max_mireds: 500
      supported_color_modes:
      - color_temp
      - onoff
      - xy
      entity_id:
      - light.living_color_lamp_1
      - light.living_color_lamp_2
      - light.living_color_lamp_3
      - light.string_lights
      - light.desk_lights
      icon: mdi:lightbulb-group
      friendly_name: Living Room Lights
      supported_features: 40
      color_mode: xy
      brightness: 255
      hs_color:
      - 38.438
      - 50.196
      rgb_color:
      - 255
      - 209
      - 127
      xy_color:
      - 0.4498
      - 0.4059
      state: 'on'
    light.bed_white_lamp_1:
      supported_color_modes:
      - brightness
      color_mode: brightness
      brightness: 255
      mode: normal
      dynamics: none
      friendly_name: Bedroom white lamp 1
      supported_features: 40
      state: 'on'
  icon: mdi:lightbulb-on-outline
  metadata:
    light.bed_white_lamp_1:
      entity_only: true
- id: '1610994787395'
  name: Full Off
  entities:
    input_boolean.sync_what_s_playing_to_lights:
      editable: true
      icon: mdi:palette
      friendly_name: Sync What's Playing to Lights?
      state: 'off'
    light.living_room_lights:
      min_mireds: 153
      max_mireds: 500
      supported_color_modes:
      - color_temp
      - onoff
      - xy
      entity_id:
      - light.living_color_lamp_1
      - light.living_color_lamp_2
      - light.living_color_lamp_3
      - light.string_lights
      - light.desk_lights
      icon: mdi:lightbulb-group
      friendly_name: Living Room Lights
      supported_features: 40
      state: 'off'
    light.bed_white_lamp_1:
      supported_color_modes:
      - brightness
      mode: normal
      dynamics: none
      friendly_name: Bedroom white lamp 1
      supported_features: 40
      state: 'off'
  icon: mdi:lightbulb-off-outline
  metadata:
    light.bed_white_lamp_1:
      entity_only: true
- id: '1610994850307'
  name: Work
  entities:
    light.desk_lights:
      supported_color_modes:
      - onoff
      friendly_name: Desk Lights
      supported_features: 0
      state: unavailable
    light.string_lights:
      supported_color_modes:
      - onoff
      friendly_name: String Lights
      supported_features: 0
      state: unavailable
    input_boolean.sync_what_s_playing_to_lights:
      editable: true
      icon: mdi:palette
      friendly_name: Sync What's Playing to Lights?
      state: 'off'
    light.black_lamp:
      supported_color_modes:
      - color_temp
      - xy
      icon: mdi:lightbulb-group
      friendly_name: Black Lamp
      supported_features: 44
      min_color_temp_kelvin: 2000
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 500
      effect_list:
      - None
      - candle
      - fire
      - unknown
      entity_id:
      - light.living_color_lamp_1
      - light.living_color_lamp_2
      - light.living_color_lamp_3
      color_mode: xy
      brightness: 253
      hs_color:
      - 38.438
      - 50.196
      rgb_color:
      - 255
      - 209
      - 127
      xy_color:
      - 0.4498
      - 0.4059
      effect: None
      state: 'on'
    light.bedroom:
      supported_color_modes:
      - brightness
      is_hue_group: true
      hue_scenes:
      - Tropical twilight
      - Dimmed
      - Energize
      - Savanna sunset
      - Mixology
      - Read
      - Concentrate
      - Spring blossom
      - Bright
      - Arctic aurora
      - Nightlight
      - Relax
      hue_type: room
      lights:
      - Bedroom white lamp 1
      dynamics: false
      icon: mdi:lightbulb-group
      friendly_name: Bedroom
      supported_features: 40
      state: 'off'
  icon: mdi:briefcase-outline
  metadata:
    light.black_lamp:
      entity_only: true
    light.bedroom:
      entity_only: true
- id: '1619984401301'
  name: Party
  entities:
    input_boolean.sync_what_s_playing_to_lights:
      editable: true
      icon: mdi:palette
      friendly_name: Sync What's Playing to Lights?
      state: 'on'
    light.desk_lights:
      supported_color_modes:
      - onoff
      friendly_name: Desk Lights
      supported_features: 0
      state: 'off'
    light.dining_lights:
      min_mireds: 153
      max_mireds: 500
      supported_color_modes:
      - color_temp
      - xy
      color_mode: xy
      brightness: 43
      hs_color:
      - 38.438
      - 50.196
      rgb_color:
      - 255
      - 209
      - 127
      xy_color:
      - 0.4498
      - 0.4059
      entity_id:
      - light.living_color_lamp_1
      - light.living_color_lamp_2
      - light.living_color_lamp_3
      icon: mdi:lightbulb-group
      friendly_name: Dining Lights
      supported_features: 40
      state: 'on'
    light.string_lights:
      supported_color_modes:
      - onoff
      color_mode: onoff
      friendly_name: String Lights
      supported_features: 0
      state: 'on'
  icon: mdi:cake
- id: '1621908839349'
  name: Relax
  entities:
    input_boolean.sync_what_s_playing_to_lights:
      editable: true
      icon: mdi:palette
      friendly_name: Sync What's Playing to Lights?
      state: 'off'
    light.desk_lights:
      supported_color_modes:
      - onoff
      friendly_name: Desk Lights
      supported_features: 0
      state: unavailable
    light.string_lights:
      supported_color_modes:
      - onoff
      friendly_name: String Lights
      supported_features: 0
      state: unavailable
    light.black_lamp:
      supported_color_modes:
      - color_temp
      - xy
      icon: mdi:lightbulb-group
      friendly_name: Black Lamp
      supported_features: 44
      min_color_temp_kelvin: 2000
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 500
      effect_list:
      - None
      - candle
      - fire
      - unknown
      entity_id:
      - light.living_color_lamp_1
      - light.living_color_lamp_2
      - light.living_color_lamp_3
      color_mode: xy
      brightness: 128
      hs_color:
      - 38.438
      - 50.196
      rgb_color:
      - 255
      - 209
      - 127
      xy_color:
      - 0.4498
      - 0.4059
      effect: None
      state: 'on'
    light.bedroom:
      supported_color_modes:
      - brightness
      is_hue_group: true
      hue_scenes:
      - Tropical twilight
      - Dimmed
      - Energize
      - Savanna sunset
      - Mixology
      - Read
      - Concentrate
      - Spring blossom
      - Bright
      - Arctic aurora
      - Nightlight
      - Relax
      hue_type: room
      lights:
      - Bedroom white lamp 1
      dynamics: false
      icon: mdi:lightbulb-group
      friendly_name: Bedroom
      supported_features: 40
      color_mode: brightness
      brightness: 128
      state: 'on'
  icon: mdi:spa
  metadata:
    light.black_lamp:
      entity_only: true
    light.bedroom:
      entity_only: true
- id: '1664949050233'
  name: Now Dining
  entities:
    light.bedroom:
      supported_color_modes:
      - brightness
      is_hue_group: true
      hue_scenes:
      - Tropical twilight
      - Dimmed
      - Energize
      - Savanna sunset
      - Mixology
      - Read
      - Concentrate
      - Spring blossom
      - Bright
      - Arctic aurora
      - Nightlight
      - Relax
      hue_type: room
      lights:
      - Bedroom white lamp 1
      dynamics: false
      icon: mdi:lightbulb-group
      friendly_name: Bedroom
      supported_features: 40
      color_mode: brightness
      brightness: 253
      state: 'on'
    light.black_lamp:
      supported_color_modes:
      - color_temp
      - xy
      icon: mdi:lightbulb-group
      friendly_name: Black Lamp
      supported_features: 44
      min_color_temp_kelvin: 2000
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 500
      effect_list:
      - None
      - candle
      - fire
      - unknown
      entity_id:
      - light.living_color_lamp_1
      - light.living_color_lamp_2
      - light.living_color_lamp_3
      color_mode: xy
      brightness: 253
      hs_color:
      - 38.438
      - 50.196
      rgb_color:
      - 255
      - 209
      - 127
      xy_color:
      - 0.4498
      - 0.4059
      effect: None
      state: 'on'
  icon: mdi:silverware-fork-knife
  metadata:
    light.bedroom:
      entity_only: true
    light.black_lamp:
      entity_only: true
- id: '1664949090634'
  name: Bedroom on
  entities:
    light.bed_white_lamp_1:
      supported_color_modes:
      - brightness
      color_mode: brightness
      brightness: 255
      mode: normal
      dynamics: none
      friendly_name: Bedroom white lamp 1
      supported_features: 40
      state: 'on'
  icon: mdi:bed-empty
  metadata: {}
- id: '1664949113299'
  name: Bedroom off
  entities:
    light.bed_white_lamp_1:
      supported_color_modes:
      - brightness
      mode: normal
      dynamics: none
      friendly_name: Bedroom white lamp 1
      supported_features: 40
      state: 'off'
  icon: mdi:bed
  metadata: {}
- id: '1665464001719'
  name: Living Room Off
  entities:
    light.living_room_lights:
      min_color_temp_kelvin: 2000
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 500
      effect_list:
      - None
      - candle
      - fire
      - unknown
      supported_color_modes:
      - color_temp
      - onoff
      - xy
      entity_id:
      - light.living_color_lamp_1
      - light.living_color_lamp_2
      - light.living_color_lamp_3
      - light.string_lights
      - light.desk_lights
      icon: mdi:lightbulb-group
      friendly_name: Living Room Lights
      supported_features: 44
      state: 'off'
  icon: mdi:lamps-outline
  metadata:
    light.living_room_lights:
      entity_only: true
- id: '1672166509043'
  name: Living Room On
  entities:
    light.living_room_lights:
      supported_color_modes:
      - brightness
      - color_temp
      - onoff
      - xy
      icon: mdi:lightbulb-group
      friendly_name: Living Room Lights
      supported_features: 44
      min_color_temp_kelvin: 2000
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 500
      effect_list:
      - None
      - candle
      - fire
      - unknown
      entity_id:
      - light.living_color_lamp_1
      - light.living_color_lamp_2
      - light.living_color_lamp_3
      - light.string_lights
      - light.desk_lights
      - light.bedroom
      color_mode: xy
      brightness: 255
      hs_color:
      - 38.438
      - 50.196
      rgb_color:
      - 255
      - 209
      - 127
      xy_color:
      - 0.4498
      - 0.4059
      effect: None
      state: 'on'
  icon: mdi:lamps
  metadata:
    light.living_room_lights:
      entity_only: true
