all_lights_off:
  alias: All Lights Off
  sequence:
  - service: scene.turn_on
    target:
      entity_id: scene.full_off
    metadata: {}
  mode: single
  icon: mdi:lightbulb-group-off
all_lights_on:
  alias: All Lights On
  sequence:
  - service: scene.turn_on
    target:
      entity_id: scene.full_on
    metadata: {}
  mode: single
  icon: mdi:lightbulb-group
living_room_lights_on:
  alias: Living Room Lights On
  sequence:
  - service: scene.turn_on
    target:
      entity_id: scene.living_room_on
    metadata: {}
  mode: single
  icon: mdi:lamps
living_room_lights_off:
  alias: Living Room Lights Off
  sequence:
  - service: scene.turn_on
    target:
      entity_id: scene.living_room_off
    metadata: {}
  mode: single
  icon: mdi:lamps-outline
bedroom_on:
  alias: Bedroom On
  sequence:
  - service: scene.turn_on
    target:
      entity_id: scene.bedroom_on
    metadata: {}
  mode: single
  icon: mdi:bed
bedroom_off:
  alias: Bedroom Off
  sequence:
  - service: scene.turn_on
    target:
      entity_id: scene.bedroom_off
    metadata: {}
  mode: single
  icon: mdi:bed-outline
relax:
  alias: Relax
  sequence:
  - service: scene.turn_on
    target:
      entity_id: scene.relax
    metadata: {}
  mode: single
  icon: mdi:spa
theater:
  alias: Theater
  sequence:
  - service: scene.turn_on
    target:
      entity_id: scene.theater_mode
    metadata: {}
  mode: single
  icon: mdi:filmstrip-box
work:
  alias: Work
  sequence:
  - service: scene.turn_on
    target:
      entity_id: scene.work
    metadata: {}
  mode: single
  icon: mdi:briefcase-outline
brighter:
  alias: Brighter
  sequence:
  - event: ios.action_fired
    event_data:
      actionID: brightness_up
      actionName: brightness_up
  mode: single
  icon: mdi:lightbulb-on
dimmer:
  alias: Dimmer
  sequence:
  - event: ios.action_fired
    event_data:
      actionID: brightness_down
      actionName: brightness_down
  mode: single
  icon: mdi:lightbulb
louder:
  alias: Louder
  sequence:
  - event: ios.action_fired
    event_data:
      actionID: volume_up
      actionName: volume_up
  mode: single
  icon: mdi:volume-high
softer:
  alias: Softer
  sequence:
  - event: ios.action_fired
    event_data:
      actionID: volume_down
      actionName: volume_down
  mode: single
  icon: mdi:volume-medium
play_in_living_room:
  alias: Play in Living Room
  sequence:
  - service: automation.trigger
    data:
      skip_condition: true
    target:
      entity_id: automation.sonos_i_living_room
  mode: single
  icon: mdi:music-box
play_in_bedroom:
  alias: Play in Bedroom
  sequence:
  - service: automation.trigger
    data:
      skip_condition: true
    target:
      entity_id: automation.sonos_ii_bedroom
  mode: single
  icon: mdi:music-circle
play_in_bathroom:
  alias: Play in Bathroom
  sequence:
  - service: automation.trigger
    data:
      skip_condition: true
    target:
      entity_id:
      - automation.sonos_iii_bathroom
  mode: single
  icon: mdi:music-box-outline
play_turntable:
  alias: Play Turntable
  sequence:
  - service: automation.trigger
    data:
      skip_condition: true
    target:
      entity_id: automation.sonos_iv_turntable
  mode: single
  icon: mdi:record-player
turn_down:
  sequence:
  - action: scene.turn_on
    metadata: {}
    target:
      entity_id: scene.turn_down
    data: {}
  alias: Turn down
  description: ''
