all_lights_off:
  alias: All Lights Off
  sequence:
  - service: scene.turn_on
    target:
      entity_id: scene.full_off
    metadata: {}
  mode: single
  icon: mdi:lightbulb-group-off
all_lights_on:
  alias: All Lights On
  sequence:
  - service: scene.turn_on
    target:
      entity_id: scene.full_on
    metadata: {}
  mode: single
  icon: mdi:lightbulb-group
living_room_lights_on:
  alias: Living Room Lights On
  sequence:
  - service: scene.turn_on
    target:
      entity_id: scene.living_room_on
    metadata: {}
  mode: single
  icon: mdi:lamps
living_room_lights_off:
  alias: Living Room Lights Off
  sequence:
  - service: scene.turn_on
    target:
      entity_id: scene.living_room_off
    metadata: {}
  mode: single
  icon: mdi:lamps-outline
bedroom_on:
  alias: Bedroom On
  sequence:
  - service: scene.turn_on
    target:
      entity_id: scene.bedroom_on
    metadata: {}
  mode: single
  icon: mdi:bed
bedroom_off:
  alias: Bedroom Off
  sequence:
  - service: scene.turn_on
    target:
      entity_id: scene.bedroom_off
    metadata: {}
  mode: single
  icon: mdi:bed-outline
relax:
  alias: Relax
  sequence:
  - service: scene.turn_on
    target:
      entity_id: scene.relax
    metadata: {}
  mode: single
  icon: mdi:spa
theater:
  alias: Theater
  sequence:
  - service: scene.turn_on
    target:
      entity_id: scene.theater_mode
    metadata: {}
  mode: single
  icon: mdi:filmstrip-box
work:
  alias: Work
  sequence:
  - service: scene.turn_on
    target:
      entity_id: scene.work
    metadata: {}
  mode: single
  icon: mdi:briefcase-outline
